### ISSUE TITLE
`Hide Shorts remix button` doesn’t work

### ISSUE THREAD

**Issue by rakleed** [arichorn/CercubePlusExtra#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: iPhone XR
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of CercubePlus (**latest** or **newest** is **NOT** a version number!): v18.01.6-5.3.11

### Describe the bug

`Hide Shorts remix button` doesn’t work under video player.

### Steps to reproduce the issue

1. Enable `Hide Shorts remix button` in CercubePlus -> Miscellaneous settings
2. Restart YouTube app
3. Open https://youtu.be/jqE8M2ZnFL8, for example

### Are you using the newest version of CercubePlus? If not, why?

✅ Yes, I'm using the latest version of CercubePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Or is this function doing something else?

<details><summary>Screenshots</summary>

![0039A89A-A70C-46EE-A5ED-EAA4BF65E8F6](https://user-images.githubusercontent.com/19418601/212508981-39ad0472-1d48-4cde-be7f-1f89d23ad5ba.png)

![D5387F69-F359-4246-9F1A-E53B06E75D6F](https://user-images.githubusercontent.com/19418601/212509015-108508ec-c345-49cf-9d85-7d22d694ceba.png)

</details>

**Comment by arichorn** [comment]
Hey umm. I don’t think this is an issue. the Option disables “Hide Shorts Remix” in the shorts video player. Not the one shown in the original video player. But hey it is a good feature request so I’ll try adding another option for it if I figure out how to hide those buttons

**Comment by rakleed** [comment]
Thanks for the quick response! If you can figure out how to hide this button, then I would also like to be able to hide the Clip button in the same section, since I have never used these buttons. But I sometimes use the Save button when I start watching a video, and deciding to postpone watching it for later, I use it to add a video to Watch Later. But I have to scroll to it because of the useless Remix and Clip buttons for me.

**Comment by arichorn** [comment]
The problem is that the Remix and Clip Buttons are using `_ASDisplayView` which makes stuff Client-side which makes it really hard to hide those buttons but I’ll try.
