### ISSUE TITLE
[Feature Request] Add “Hide SponsorBlock Button”

### ISSUE THREAD

**Issue by yusuf0142** [arichorn/CercubePlusExtra#11]
###
Any way you could put an option in CercubePlus settings to hide the iSponsorBlock icon on the navigation bar?

It just looks so ugly and I would really really appreciate it.

**Comment by arichorn** [comment]
I readed your suggestion and thought I could do it but based on the commits I’ve done, I pretty much failed to add the ability to hide the SponsorBlock button but I’ll still try to add it in.

**Comment by yusuftuncay** [comment]
It seems so simple, but is probably harder to do. I really appreciate you trying!

Also, out of all the tweaked YouTube apps, I like this one 100%, thanks a lot.

**Comment by arichorn** [comment]
No problem! I didn’t want CercubePlus gone but glad I kept the forked repository!

**Comment by arichorn** [comment]
Dayanch96 has added the option, use the latest release to be able to use it! [v18.04.3-5.3.11](https://github.com/arichorn/CercubePlusExtra/releases/tag/v18.04.3-5.3.11)
