### ISSUE TITLE
[Bug] YTNoModernUI cannot be disabled

### ISSUE THREAD

**Issue by rakleed** [arichorn/CercubePlusExtra#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.3
- Device model: iPhone XR
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of CercubePlus (**latest** or **newest** is **NOT** a version number!): [v18.04.3-5.3.11](https://github.com/arichorn/CercubePlusExtra/releases/tag/v18.04.3-5.3.11)

### Describe the bug

Hide Modern Interface (YTNoModernUI) cannot be disabled.

### Steps to reproduce the issue

1. Click on user icon
2. Go to Settings
3. Go to CercubePlus
4. Go to Customization Options
5. Disable Hide Modern Interface
6. Reload app
7. Go to the same setting

### Are you using the newest version of CercubePlus? If not, why?

✅ Yes, I'm using the latest version of CercubePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

It is enough to disable Hide Modern Interface, exit Customization Options and go back to them, and the option will already be enabled again.

<details><summary>Screen recording</summary>

https://user-images.githubusercontent.com/19418601/218277914-49252b78-5f33-4f75-9e2c-af554f3213f8.MP4

</details>

**Comment by arichorn** [comment]
this issue is fixed in [CercubePlusExtra 18.05.2-5.3.11 Beta](https://github.com/arichorn/CercubePlusExtra/releases/download/v18.05.2-5.3.11-beta/CercubePlusExtra_18.05.2_5.3.11_beta.ipa)
Also this is a beta so if YouTube Shorts Crashes blame Google.

**Comment by rakleed** [comment]
Yep, that section has now been removed.

Do you mean if YouTube Shorts are disabled? Since I have them disabled, and so far the application has never crashed.

**Comment by arichorn** [comment]
Oh then Cercube must be different, because for me I use uYouPlus and it has been crashing. Thanks for letting me know though. 👍

**Comment by rakleed** [comment]
I also brought back YouTube Shorts, and the app doesn't crash when viewing them.

**Comment by arichorn** [comment]
> I also brought back YouTube Shorts, and the app doesn't crash when viewing them.

Worth noting Ty.
