### ISSUE TITLE
Pls pls don’t archive this repo

### ISSUE THREAD

**Issue by Ketarmin** [arichorn/CercubePlusExtra#2]
Is there any chance to fork your fork ? 

I like Cercube much more then uYouplus but unfortunately the repo of QN got taken down but no one knows why

**Comment by arichorn** [comment]
> Is there any chance to fork your fork ?
yes of course! And if you need help go here. https://github.com/arichorn/CercubePlusExtra/wiki/Building

> I like Cercube much more then uYouplus but unfortunately the repo of QN got taken down but no one knows why
I think the reason it got taken down was probably because it got requested for take down by the Cercube Developer or Google sent qn a letter to take it down. Honestly don’t know but this is probably why I’m Archiving to prevent the same fate as the original CercubePlus Repo

also when this gets archived you can still download the cercubeplus ipa.

**Comment by Ketarmin** [comment]
> > I like Cercube much more then uYouplus but unfortunately the repo of QN got taken down but no one knows why
> > I think the reason it got taken down was probably because it got requested for take down by the Cercube Developer or Google sent qn a letter to take it down. Honestly don’t know but this is probably why I’m Archiving to prevent the same fate as the original CercubePlus Repo

hm okay i really wish that you maintain it as long as possible, i have not enough knowledge to do it by myself :(.
 
i think not that he does it because of the Cercube Dev want it too, QN never cracked it, he just combined it with other tweaks like on jailbreak.

The take down is really really mysterious

**Comment by eyeslow** [comment]
I would highly recommend to not mention "Cercube" anywhere, I think it's developer is continuously searching the web for unauthorised projects from people using his tweak and is sending out injunctions... So many Cercube Mods were taken down in the past...

**Comment by Ketarmin** [comment]
> I would highly recommend to not mention "Cercube" anywhere, I think it's developer is continuously searching the web for unauthorised projects from people using his tweak and is sending out injunctions... So many Cercube Mods were taken down in the past...

Really?  It’s really hard for me to imagine that the dev of Cercube would do something like that because his tweak is not modified/ cracked in the CercubePlus ipa

**Comment by Ketarmin** [comment]
> Sadly for me I have no knowledge I know a bit though when it comes to changing a bit of stuff in the code. but overall it’s not bad.

okay, same for me
> 
> Yep I can combine tweaks like qn too. Like for example the New YT Shorts remover Tweak I added in 17.49.4-5.3.12. Combining tweaks is pretty simple if you find some tutorials about it.


Ok maybe you can teach me some of your knowledge ;)
Or give a link for good video

**Comment by arichorn** [comment]
> > I would highly recommend to not mention "Cercube" anywhere, I think it's developer is continuously searching the web for unauthorised projects from people using his tweak and is sending out injunctions... So many Cercube Mods were taken down in the past...

Yeah. It’s been sad to see them go.

> Really? It’s really hard for me to imagine that the dev of Cercube would do something like that because his tweak is not modified/ cracked in the CercubePlus ipa

Cercube itself wasn’t modified in this. It’s just sad to see the dev take them down.

> I think I will ask him

watch out. Don’t let this get taken down, because I got a bit more versions to go before I stop maintaining it.

**Comment by Ketarmin** [comment]
B
