### ISSUE TITLE
The latest version crashes 

### ISSUE THREAD

**Issue by Ketarmin** [arichorn/CercubePlusExtra#5]
Hey, so the latest version you offer on the release page starts to crash as of today 

it opens then tries to load the front page and in that moment it crashes 

Did you see that happening to uYou+ from Qn too ? 

link: https://youtube.com/shorts/viipC45ZuFU?feature=share

**Comment by Ketarmin** [comment]
The crash have something to do with the injected tweaks, because I tried your tweak collection with the YT v17.43.1 and it behave like your latest version 49.4 (you can find them on my fork) 

I compared it with latest orig CercubePlus version from Qn which was v17.43.1

**Comment by arichorn** [comment]
Hmm interesting.. I’ll suppose it’s either the new tweak I added or YouTube breaking Cercube but I’ll see if I can resolve it

**Comment by Ketarmin** [comment]
The strange thing is that it work with no problem one day before I opened this issue 

maybe it’s the latest Cercube version

**Comment by arichorn** [comment]
you are right. I went on reddit and it was the latest Cercube version. I think Cercube is dead but the only things that will work is probably the features within Cercube.

**Comment by arichorn** [comment]
https://github.com/arichorn/CercubePlusExtra/issues/6 I will also disable one of the cercube features that won't work anymore by default in a POLL I'm doing.

**Comment by arichorn** [comment]
https://github.com/arichorn/CercubePlusExtra/releases/tag/v17.49.6-5.3.11-(47) try this

**Comment by Ketarmin** [comment]
> https://github.com/arichorn/CercubePlusExtra/releases/tag/v17.49.6-5.3.11-(47) try this

Yes, fixed the crashing
