### ISSUE TITLE
[Bug] CercubePlus options not working

### ISSUE THREAD

**Issue by mystrd** [arichorn/CercubePlusExtra#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: iPad Pro 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!):

### Describe the bug

Many thanks for keeping this ipa alive. Having an issue whereby in the CercubePlus options not pulling through after latest update (v18.0.2). I cannot hide Cast bar or Video Player buttons despite selecting them in the Cercube Plus settings submenu. Not sure if this has something to do with the latest rejig of the settings menu.

### Steps to reproduce the issue

1. Modify options in latest version (v18.0.2)

### Are you using the newest version of CercubePlus? If not, why?

✅ Yes, I'm using the latest version of CercubePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by arichorn** [comment]
Sorry for not responding, but can you show me a video or a screenshot of what this issue looks like? Gotta understand and see if I can fix it.

**Comment by mystrd** [comment]
https://user-images.githubusercontent.com/68656518/212061923-068f4360-1a26-4e5b-b8ce-6a5bf88a4159.mov

**Comment by mystrd** [comment]
https://user-images.githubusercontent.com/68656518/212062161-5f389aca-f005-426b-8eda-87f116724ae2.mov

As you can see despite choosing the above settings, they don't then hide those elements. 
Hiding shorts option also doesn't stick.

**Comment by arichorn** [comment]
Being honest. Hiding Shorts Options are meant to only be for the Shorts tab. it does not effect the video player at all because that's just how YouTube is. also I'm fixing some of the issues.

**Comment by mystrd** [comment]
Ah okay, many thanks!

**Comment by arichorn** [comment]
I'm about to release the new version I'll msg you when I release it rn

**Comment by arichorn** [comment]
[v18.01.4-5.3.11](https://github.com/arichorn/CercubePlusExtra/releases/tag/v18.01.4-5.3.11-(89)) here ya go!

**Comment by mystrd** [comment]
Working great now, many thanks for the speedy fix!

**Comment by arichorn** [comment]
No Problem!
