### ISSUE TITLE
[Bug] Hide "Shorts" toggle not persisting

### ISSUE THREAD

**Issue by aryaziai** [arichorn/CercubePlusExtra#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- Cercube v18.01.4-5.3.11

### Describe the bug

All of the "Shorts" settings persist except for when I turn on "Hide shorts videos"

### Steps to reproduce the issue

Settings > CercubePlus > Shorts Controls Overlay Options.

Checkmark the first option.

### Are you using the newest version of CercubePlus? If not, why?

✅ Yes, I'm using the latest version of CercubePlus right now

**Comment by arichorn** [comment]
Can you show me an image/video of this issue?

Just so you know the options
Hide Shorts Like Button and any other option below only effects the Shorts Tab. I may rebrand the “Shorts Overlay Options” name to prevent confusion in settings.

**Comment by arichorn** [comment]
That’s odd. There is a fix for this type of issue but I’m afraid I will have take out the HideShorts option in “Shorts Controls Overlay Options”
It won’t be removed I’m saying that there’s a possible fix for this type of problem

**Comment by arichorn** [comment]
[v18.01.6-5.3.11](https://github.com/arichorn/CercubePlusExtra/releases/tag/v18.01.6-5.3.11)
Hopefully the option should be solved! 👍

**Comment by arichorn** [comment]
> Btw, I subscribed to the release notes so I look forward to seeing all your awesome work in the future

Well I’m not a really good coder being honest. I was able to fix the issue because I have code saved from the old CercubePlus repository. and some most features were copy and pasted except for my own tweaks

**Comment by arichorn** [comment]
Oh alright. But anyways, gotta say. is the Shorts issue & Customization Options Localization fixed?
I fixed 2 issues and updated Submodules this release

**Comment by arichorn** [comment]
> Unrelated question: Do you know if there is a way to not be forced to re-do all the settings each time I install a sideloaded app again? (I'm using sideloadly on my computer)

I forgot to answer. Using the tool AltStore to sideload apps keeps the data saved and you’ll keep the setting options you have toggled on.

**Comment by arichorn** [comment]
> I still see shorts in my subscription tab like in my video recording example, but I'm guessing that's not fixable

Didn’t know what you meant at first the subscription tab in shorts? this issue can be fixable but I don’t know if I can even fix that since I haven’t researched which method it uses to disable it.

**Comment by arichorn** [comment]
latest release does some pretty small changes to hideShorts, hope it still works fine. [v18.04.3-5.3.11](https://github.com/arichorn/CercubePlusExtra/releases/tag/v18.04.3-5.3.11)

**Comment by rakleed** [comment]
@arichorn the feature description is very short https://github.com/arichorn/CercubePlusExtra/blob/f11083b5eb297afd16de03ca17f10b2962122142/lang/CercubePlus.bundle/en.lproj/Localizable.strings#L139-L140 but I understand that this feature does not hide the Shorts tab when viewing channel information? Is it possible to hide this tab too?

<details><summary>Screenshot</summary>

![IMG_6B40C136A171-1](https://user-images.githubusercontent.com/19418601/216791438-944b122c-6e41-48cd-bbf0-37cdb618f577.jpeg)

</details>

**Comment by arichorn** [comment]
> but I understand that this feature does not hide the Shorts tab when viewing channel information? Is it possible to hide this tab too?

sure I'll see if I can do that next release.
